[package]
name = "hecto"
version = "0.1.0"
authors = ["Noah Zbozny <nezbozny@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
